import { jsPDF } from 'jspdf';

/**
 * Generate a print-ready PDF from menu data
 */
export async function generatePDF(menuData, outputPath) {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
    compress: true,
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - 2 * margin;

  let yPosition = margin;

  // Title
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');

  const restaurantName = inferRestaurantName(menuData);
  doc.text(restaurantName, pageWidth / 2, yPosition, { align: 'center' });
  yPosition += 15;

  // Subtitle or tagline
  doc.setFontSize(10);
  doc.setFont('helvetica', 'italic');
  const tagline = generateTagline(menuData.context);
  doc.text(tagline, pageWidth / 2, yPosition, { align: 'center' });
  yPosition += 15;

  // Separator line
  doc.setLineWidth(0.5);
  doc.line(margin, yPosition, pageWidth - margin, yPosition);
  yPosition += 10;

  // Render sections
  for (const section of menuData.structure.sections) {
    // Check if we need a new page
    if (yPosition > pageHeight - 40) {
      doc.addPage();
      yPosition = margin;
    }

    // Section header
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text(section.name, margin, yPosition);
    yPosition += 8;

    // Section items
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);

    for (const item of section.items) {
      // Check page break
      if (yPosition > pageHeight - 30) {
        doc.addPage();
        yPosition = margin;
      }

      // Item name and price on same line
      doc.setFont('helvetica', 'bold');
      const price = item.prices && item.prices.length > 0 ? `$${item.prices[0].toFixed(2)}` : '';
      const nameWidth = contentWidth - 30;

      doc.text(item.name || 'Unnamed Item', margin, yPosition);

      if (price) {
        doc.text(price, pageWidth - margin, yPosition, { align: 'right' });
      }

      yPosition += 5;

      // Description
      if (item.description && item.description.trim()) {
        doc.setFont('helvetica', 'italic');
        doc.setFontSize(9);

        const descLines = doc.splitTextToSize(item.description, contentWidth);
        doc.text(descLines, margin + 5, yPosition);
        yPosition += descLines.length * 4;
      }

      yPosition += 6; // Space between items
    }

    yPosition += 5; // Space between sections
  }

  // Add footer with generation date
  const totalPages = doc.internal.pages.length - 1;
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.text(
      `Generated by Menu Chef - ${new Date().toLocaleDateString()}`,
      pageWidth / 2,
      pageHeight - 10,
      { align: 'center' }
    );
  }

  // Save to file
  await doc.save(outputPath);
}

function inferRestaurantName(menuData) {
  // Try to infer from first section or default
  if (menuData.structure.sections.length > 0) {
    const firstLine = menuData.structure.rawLines[0];
    if (firstLine && firstLine.length < 50 && !firstLine.includes('$')) {
      return firstLine;
    }
  }

  return 'Restaurant Menu';
}

function generateTagline(context) {
  if (context.cuisineType && context.cuisineType !== 'general') {
    return `Authentic ${context.cuisineType.charAt(0).toUpperCase() + context.cuisineType.slice(1)} Cuisine`;
  }
  return 'Fine Dining Experience';
}
