import React, { useEffect, useRef } from 'react';
import './MenuPreview.css';

function MenuPreview({ menuData }) {
  const previewRef = useRef(null);

  useEffect(() => {
    if (previewRef.current && menuData) {
      // Scroll to top when menu updates
      previewRef.current.scrollTop = 0;
    }
  }, [menuData]);

  if (!menuData) {
    return (
      <div className="menu-preview">
        <div className="preview-placeholder">
          No menu data available
        </div>
      </div>
    );
  }

  const { structure, context } = menuData;

  return (
    <div className="menu-preview" ref={previewRef}>
      <div className="menu-document">
        <div className="menu-header">
          <h1 className="menu-title">
            {inferRestaurantName(structure)}
          </h1>
          <p className="menu-tagline">
            {generateTagline(context)}
          </p>
          <div className="menu-divider"></div>
        </div>

        <div className="menu-body">
          {structure.sections.length > 0 ? (
            structure.sections.map((section, sectionIndex) => (
              <div key={sectionIndex} className="menu-section">
                <h2 className="section-title">{section.name}</h2>
                <div className="section-items">
                  {section.items.map((item, itemIndex) => (
                    <div key={itemIndex} className="menu-item">
                      <div className="item-header">
                        <h3 className="item-name">{item.name || 'Unnamed Item'}</h3>
                        <span className="item-price">
                          {item.prices && item.prices.length > 0
                            ? `$${item.prices[0].toFixed(2)}`
                            : ''}
                        </span>
                      </div>
                      {item.description && (
                        <p className="item-description">{item.description}</p>
                      )}
                    </div>
                  ))}
                </div>
              </div>
            ))
          ) : (
            <div className="menu-section">
              <h2 className="section-title">Menu Items</h2>
              <div className="section-items">
                {structure.items.map((item, itemIndex) => (
                  <div key={itemIndex} className="menu-item">
                    <div className="item-header">
                      <h3 className="item-name">{item.name || 'Unnamed Item'}</h3>
                      <span className="item-price">
                        {item.prices && item.prices.length > 0
                          ? `$${item.prices[0].toFixed(2)}`
                          : ''}
                      </span>
                    </div>
                    {item.description && (
                      <p className="item-description">{item.description}</p>
                    )}
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>

        <div className="menu-footer">
          <p>Generated by Menu Chef • {new Date().toLocaleDateString()}</p>
        </div>
      </div>
    </div>
  );
}

function inferRestaurantName(structure) {
  if (structure.rawLines && structure.rawLines.length > 0) {
    const firstLine = structure.rawLines[0];
    if (firstLine && firstLine.length < 50 && !firstLine.includes('$')) {
      return firstLine;
    }
  }
  return 'Restaurant Menu';
}

function generateTagline(context) {
  if (context && context.cuisineType && context.cuisineType !== 'general') {
    const cuisineCapitalized = context.cuisineType
      .split('/')
      .map(c => c.charAt(0).toUpperCase() + c.slice(1))
      .join(' & ');
    return `Authentic ${cuisineCapitalized} Cuisine`;
  }
  return 'Fine Dining Experience';
}

export default MenuPreview;
